# Generated by Django 2.1 on 2019-04-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter1', models.IntegerField()),
                ('parameter2', models.IntegerField()),
                ('parameter3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reklamasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('parameter1', models.IntegerField()),
                ('parameter2', models.IntegerField()),
                ('parameter3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='segmenRCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmen', models.FloatField(default='75')),
            ],
        ),
        migrations.AddField(
            model_name='rci',
            name='segmen',
            field=models.OneToOneField(default='75', on_delete=django.db.models.deletion.DO_NOTHING, to='matriks.segmenRCI'),
        ),
    ]
