# Generated by Django 2.1 on 2019-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriks', '0002_auto_20190424_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rci',
            name='segmen',
            field=models.CharField(choices=[('KM 75', '75'), ('75.5', 'KM75.5')], max_length=10),
        ),
    ]
